# Contains a dictionary of furniture types with synonyms
PRODUCT_DICTIONARY = {
    "Sofa": 
        [ 
            "couch", "loveseat", "settee", "divan", "davenport",
            "chesterfield", "sectional", "fainting couch"
        ],
    "Armchair": 
        [
            "chair", "easy chair", "wing chair", "recliner", 
            "club chair", "tub chair", "slipper chair"
        ],
    "Ottoman":
        [
            "footstool", "pouf", "pouffe", "storage ottoman", "ottoman bench",
            "cocktail ottoman", "footrest", "ottoman seat", "low stool",
            "living room stool", "sofa stool", "cube ottoman", "padded stool",
            "floor cushion", "upholstered stool", "ottoman table", "coffee table ottoman",
            "shoe bench", "lounge ottoman", "round ottoman", "square ottoman",
            "rectangle ottoman", "decorative stool", "multi-purpose stool", "accent stool"
        ],
    "Chaise Lounge":
        [
            "lounge chair", "reclining chair", "fainting couch", "daybed",
            "sunbed", "deck chair", "divan", "sofa lounger", "recliner lounge",
            "chaise sofa", "outdoor lounger", "indoor lounger", "patio lounger",
            "beach lounger", "long chair", "modern lounger", "lazy lounger",
            "comfort lounger", "curved lounge", "adjustable lounger", "studio lounger",
            "relaxation bed", "stretch chair", "oversized lounger", "media lounger"
        ],
    "Lounge Chair":
        [
            "lounger", "accent chair", "reading chair", "indoor recliner",
            "poolside chair", "deck chair", "relaxing chair", "easy chair",
            "leisure chair", "balcony chair", "patio chair", "low recliner",
            "casual chair", "modern recliner", "comfort chair", "TV chair",
            "plush chair", "living room chair", "den chair", "arm-less recliner",
            "slanted chair", "sofa recliner", "lounge seat", "lazy chair",
            "sunroom chair"
        ] 
}

# Material entities
MATERIALS = [
    'wood', 'wooden', 'leather', 'fabric', 'metal', 'steel', 
    'glass', 'plastic', 'velvet', 'cotton', 'linen', 'metallic'
]

# Color entities
COLORS = [
    'black', 'white', 'brown', 'red', 'blue', 'green', 
    'yellow', 'gray', 'grey', 'beige', 'cream'
]

# Add entity labels
ENTITY_LABELS = ['PRODUCT', 'MATERIAL', 'COLOR', 'PRICE', 'LOCATION', 'FEATURE']

# Currency patterns for price extraction
CURRENCY_PATTERNS = {
    'INR': [r'₹', r'rs\.?', r'rupees?', r'inr'],
    'USD': [r'\$', r'dollars?', r'usd', r'dollar?'],
    'EUR': [r'€', r'euros?', r'eur', r'euro?'],
    'GBP': [r'£', r'pounds?', r'gbp', r'pounds?']
}

# Need to update this
# Dimension extraction patterns
DIMENSION_PATTERNS = {
    'length': r'(?:length|long|l)\s*(?:of|is)?\s*(\d+(?:\.\d+)?)\s*(cm|m|inches?|ft|feet)',
    'width': r'(?:width|wide|w)\s*(?:of|is)?\s*(\d+(?:\.\d+)?)\s*(cm|m|inches?|ft|feet)',
    'height': r'(?:height|tall|h)\s*(?:of|is)?\s*(\d+(?:\.\d+)?)\s*(cm|m|inches?|ft|feet)'
}

# Extract quantity hints
QUANTITY_PATTERNS = [
    r'(\d+)\s*(?:pieces?|pcs?|units?|nos?)',
    r'(?:pair of|set of)\s*(\d+)',
]
# Need to add till here

# Price extraction patterns
PRICE_PATTERNS = [
    # Indian currency contextual patterns
    r'(?:under|below|less\s+than|within|up\s+to|max|maximum)\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)\s*(?:rupees?|rs\.?|₹)?',
    r'(?:above|over|more\s+than|starting\s+from|min|minimum)\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)\s*(?:rupees?|rs\.?|₹)?',

    # Explicit ranges
    r'₹\s*(\d+(?:,\d+)*(?:\.\d+)?)\s*(?:to|-)\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)',
    r'(\d+(?:,\d+)*(?:\.\d+)?)\s*(?:to|-)\s*(\d+(?:,\d+)*(?:\.\d+)?)(?:\s*(?:rupees?|rs\.?|₹))?',
    r'price\s*(?:range|is)?\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)\s*(?:to|-)\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)(?:\s*(?:rupees?|rs\.?|₹))?',

    # Between X and Y (covers rupees, dollars, euros, etc.)
    r'(?:between)\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)\s*(?:and|-)\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)(?:\s*(?:rupees?|rs\.?|₹|\$|dollars?|€|euros?|£|pounds?))?',

    # Budget style
    r'budget\s*(?:of|is|around)?\s*₹?\s*(\d+(?:,\d+)*(?:\.\d+)?)(?:\s*(?:rupees?|rs\.?|₹))?',

    # Single values (catch-all)
    r'(\d+(?:,\d+)*(?:\.\d+)?)(?:\s*(?:rupees?|rs\.?|₹|\$|dollars?|€|euros?|£|pounds?))',
    r'(?:₹|\$|€|£)\s*(\d+(?:,\d+)*(?:\.\d+)?)',
]

# Number patterns for price extraction
NUMBER_PATTERNS = [
    r'(\d+(?:,\d+)*(?:\.\d+)?)',  # Standard numbers with commas
    r'(\d+(?:\.\d+)?)\s*(?:k|thousand|thous)',  # 5k, 10 thousand
    r'(\d+(?:\.\d+)?)\s*(?:l|lakh|lac)',  # 2 lakh
    r'(\d+(?:\.\d+)?)\s*(?:cr|crore)',   # 1 crore
]

# Pattern for price ranges: X-Y, X to Y, between X and Y
RANGE_PATTERNS = [
    r'(\d+[\d,.]*)\s*[-–—to]\s*(\d+[\d,.]*)',  # X-Y or X to Y
    r'between\s+(\d+[\d,.]*)\s+and\s+(\d+[\d,.]*)',  # between X and Y
    r'(\d+[\d,.]*)\s*and\s*(\d+[\d,.]*)'  # X and Y
]

# Analyze context around numbers
CONTEXT_WORDS = {
    'max': ['under', 'below', 'less', 'within', 'budget', 'maximum', 'max', 'up to'],
    'min': ['above', 'over', 'more', 'starting', 'minimum', 'min', 'from'],
    'range': ['between', 'to', 'and', 'from', 'range'],
    'exact': ['price', 'cost', 'worth', 'value', 'amount', 'total', 'around', 'about']
}

# Furniture configuration for entity recognition
FURNITURE_CONFIG = {
    'products': {
        'sofa': ['sofa', 'couch', 'sectional', 'loveseat', 'settee'],
        'chair': ['chair', 'armchair', 'recliner', 'rocker', 'accent chair'],
        'table': ['table', 'coffee table', 'dining table', 'side table', 'console table'],
        'bed': ['bed', 'mattress', 'bed frame', 'platform bed', 'storage bed'],
        'storage': ['dresser', 'wardrobe', 'cabinet', 'bookshelf', 'chest of drawers']
    },
    'features': {
        'back': {
            'curved': ['Curved Back', 'Curved Backrest'],
            'straight': ['Straight Back', 'Linear Backrest'],
            'high': ['High Back', 'Tall Backrest'],
            'low': ['Low Back', 'Short Backrest']
        },
        'legs': {
            'slanted': ['Inclined Leg', 'Angled Leg'],
            'straight': ['Straight Leg', 'Vertical Leg'],
            'tapered': ['Tapered Leg', 'Narrowing Leg']
        },
        'material': {
            'leather': ['Leather', 'Genuine Leather'],
            'fabric': ['Fabric', 'Textile'],
            'wood': ['Wood', 'Wooden'],
            'metal': ['Metal', 'Metallic']
        },
    },
    'locations': [
        'mumbai', 'delhi', 'bangalore', 'chennai', 'kolkata', 'hyderabad',
        'pune', 'ahmedabad', 'surat', 'jaipur', 'lucknow', 'kanpur',
        'nagpur', 'indore', 'bhopal', 'visakhapatnam', 'patna', 'vadodara'
    ]
}

# Entity templates for furniture-related queries
ENTITY_TEMPLATES = [
    ("Looking for a {product} with {material} {feature}", 
    [(14, 18, 'PRODUCT'), (24, 31, 'MATERIAL'), (32, 39, 'FEATURE')]),
    ("I need a {color} {product} under {price} rupees",
    [(9, 14, 'COLOR'), (15, 20, 'PRODUCT'), (27, 32, 'PRICE')]),
    ("Show me {material} {product} with {feature} in {location}",
    [(8, 15, 'MATERIAL'), (16, 21, 'PRODUCT'), (27, 34, 'FEATURE'), (38, 46, 'LOCATION')]),
]

# Generate examples from templates
PRODUCTS_TEMP = ['sofa', 'chair', 'table', 'bed']
FEATURES_TEMP = ['curved back', 'straight legs', 'padded arms']
PRICES_TEMP = ['15000', '25000', '50000']

# Advanced pattern matching with context
FEATURE_PATTERNS = {
    'Back': [
        (r'(curvy|curved|curve)\s+back', 'Curved Back'),
        (r'back.*?(curvy|curved|curve)', 'Curved Back'),
        (r'(straight|flat)\s+back', 'Straight Back'),
        (r'(high|tall|high_back)\s+back', 'High Back'),
        (r'(low|short|low_back)\s+back', 'Low Back'),
        (r'(tufted|buttoned|quilted)\s+back', 'Tufted Back'),
        (r'(winged|wing|wing_back)\s+back', 'Winged Back'),
        (r'(winged|wing|wing_back)\s+back', 'Winged Back'),
        (r'(ladder|ladder-back)\s+back', 'Ladder Back'),
        (r'(slat|slatted|slat_back)\s+back', 'Slatted Back'),
        (r'(medium)\s+back', 'Medium Back'),
        (r'(pillow)\s+back', 'Pillow Back')
    ],
    'Legs': [
        (r'(slanted|inclined|angled)\s+legs?', 'Inclined Leg'),
        (r'legs?.*?(slanted|inclined|angled)', 'Inclined Leg'),
        (r'(straight|vertical)\s+legs?', 'Straight Leg'),
        (r'(tapered|tapering)\s+legs?', 'Tapered Leg'),
        (r'(wooden|wood)\s+legs?', 'Wooden Leg'),
        (r'legs?.*?(wooden|wood)', 'Wooden Leg'),
        (r'(metal|metallic|steel|chrome)\s+legs?', 'Metal Leg'),
        (r'legs?.*?(metal|metallic|steel|chrome)', 'Metal Leg'),
        (r'(hairpin|hair-pin)\s+legs?', 'Hairpin Leg'),
        (r'legs?.*?(hairpin|hair-pin)', 'Hairpin Leg'),
        (r'(block|square)\s+legs?', 'Block Leg'),
        (r'legs?.*?(block|square)', 'Block Leg'),
        (r'(turned|carved)\s+legs?', 'Turned Leg'),
        (r'legs?.*?(turned|carved)', 'Turned Leg'),
        (r'(curved|curvy)\s+legs?', 'Curved Leg'),
        (r'legs?.*?(curved|curvy)', 'Curved Leg'),
        (r'(pedestal|pedestal-style)\s+legs?', 'Pedestal Leg'),
        (r'legs?.*?(pedestal|pedestal-style)', 'Pedestal Leg'),
        (r'(four|4|four_legs)\s+legs?', 'Four Legs'),
        (r'legs?.*?(four|4|four_legs)', 'Four Legs'),
        (r'(sleigh|sled|sled_base)\s+legs?', 'Sleigh Leg'),
        (r'legs?.*?(sleigh|sled|sled_base)', 'Sleigh Leg'),
        (r'(crossed|cross)\s+legs?', 'Crossed Leg'),
        (r'legs?.*?(crossed|cross)', 'Crossed Leg'),
        (r'(swivel|rotating)\s+legs?', 'Swivel Leg'),
        (r'legs?.*?(swivel|rotating)', 'Swivel Leg'),
        (r'(caster|wheeled)\s+legs?', 'Caster Leg'),
        (r'legs?.*?(caster|wheeled)', 'Caster Leg'),
        (r'(trestle|trestle-style)\s+legs?', 'Trestle Leg'),
        (r'legs?.*?(trestle|trestle-style)', 'Trestle Leg'),
    ],        
    'Structure': [
        (r'(metal|metallic)\s+(?:design|detail|accent|element)', 'Metal Detail'),
        (r'some\s+(metal|metallic)', 'Metal Detail'),
        (r'with.*?(metal|metallic)', 'Metal Detail'),
        (r'(wooden|wood)\s+(?:frame|structure)', 'Wooden Frame'),
        (r'(steel|metal)\s+(?:frame|structure)', 'Steel Frame'),
        (r'(reinforced|solid)\s+(?:construction|build)', 'Solid Construction'),
    ],
    'Arms': [
        (r'(padded|cushioned)\s+arms?', 'Padded Arms'),
        (r'(rolled|curved)\s+arms?', 'Rolled Arms'),
        (r'(straight|track)\s+arms?', 'Straight Arms'),
        (r'(wide|broad)\s+arms?', 'Wide Arms'),
        (r'(wooden|wood)\s+arms?', 'Wooden Arms'),
        (r'(round|rounded)\s+arms?', 'Rounded Arms'),
        (r'(winged|wing)\s+arms?', 'Winged Arms'),
        (r'(armless|no\s+arms)', 'Armless'),
        (r'(wraparound|enveloping)\s+arms?', 'Wraparound Arms'),
        (r'(adjustable|retractable)\s+arms?', 'Adjustable Arms'),
        (r'(sleek|minimalist)\s+arms?', 'Sleek Arms'),
        (r'(square|boxy)\s+arms?', 'Square Arms'),
        (r'(sculpted|shaped)\s+arms?', 'Sculpted Arms'),
        (r'(tapered|narrow)\s+arms?', 'Tapered Arms'),
        (r'(metal|metallic)\s+arms?', 'Metal Arms'),
        (r'(track|track-style)\s+arms?', 'Track Arms'),
        (r'(English|english)\s+arms?', 'English Arms'),
        (r'(sock|sock-style)\s+arms?', 'Sock Arms'),
        (r'(t-cushion|t-cushion-style)\s+arms?', 'T-Cushion Arms')
    ],        
    'Seat': [
        (r'(deep|plush)\s+seat', 'Deep Seat'),
        (r'(firm|hard)\s+seat', 'Firm Seat'),
        (r'(soft|cushioned)\s+seat', 'Soft Seat'),
        (r'memory\s+foam', 'Memory Foam Seat'),
        (r'(sectional)', 'Sectional Seating'),
        (r'(loveseat)', 'Loveseat Seating'),
        (r'(3-seater|3\s+seater)', '3-Seater Seating'),
        (r'(2-seater|2\s+seater)', '2-Seater Seating'),
        (r'(reclining)', 'Reclining Seating'),
        (r'(upholstered)', 'Upholstered Seating'),
        (r'(woven)', 'Woven Seating'),
    ],
    'Color': [
        (r'(black)', 'Black'),
        (r'(white)', 'White'),
        (r'(brown)', 'Brown'),
        (r'(red)', 'Red'),
        (r'(blue)', 'Blue'),
        (r'(green)', 'Green'),
        (r'(yellow)', 'Yellow'),
        (r'(gray|grey)', 'Gray')
    ]
}

# Location patterns
LOCATION_PATTERNS = [
    r'in\s+([a-zA-Z\s]+)(?:\s|$)',
    r'at\s+([a-zA-Z\s]+)(?:\s|$)',
    r'from\s+([a-zA-Z\s]+)(?:\s|$)'
]

# Path to dataset
FLIPKART_DATASET_PATH = "datasets/flipkart_furniture_dataset"
MERGED_DATASET_PATH = "datasets/merged_files"

# This file contains a dictionary of country with synonyms, spelling variations and region.
PLACE_DICTIONARY = [
    {
        "feature": "Spain",
        "spelling_variations": [
            "Sapin", "Spian", "Spian ", "Spainn", "SPain", "SPain ", "Spain ",
            "Span", "Spian ", "Spainn ", "Spaian", "Spaon", "Spaim", "Spianm", "Spsain"
        ],
        "synonyms": [
            "España",
            "Kingdom of Spain"
        ],
        "region": "Europe"
    },
    {
        "feature": "Italy",
        "spelling_variations": [
            "Itlay", "Italt", "Italy ", "Itally", "ITaly", "Itay", "Italt ",
            "Italyy", "Italty", "Itlay ", "Iatly", "Utaly", "Iraly", "Italy ", "Itlayy"
        ],
        "synonyms": [
            "Italia",
            "Italian Republic"
        ],
        "region": "Europe"
    },
    {
        "feature": "Germany",
        "spelling_variations": [
            "Germnay", "GErmany", "Germanyy", "Germayn", "Germany ", "Germnay ",
            "Germay ", "Germanyy ", "Germanny", "Geramny", "Geramany", "Germanyu",
            "Geramny ", "Germnayy", "Germanym"
        ],
        "synonyms": [
            "Deutschland",
            "Federal Republic of Germany"
        ],
        "region": "Europe"
    },
    {
        "feature": "Portugal",
        "spelling_variations": [
            "Portual", "Portgal", "Portugla", "Portuagl", "Portugal ", "PRotugal",
            "Potugal", "Portugall", "Portugala", "Portugla ", "Portigual",
            "Portugalm", "Portugaly", "Portugall ", "Potugral"
        ],
        "synonyms": [
            "Portugal",
            "Portuguese Republic"
        ],
        "region": "Europe"
    },
    {
        "feature": "Denmark",
        "spelling_variations": [
            "Denmak", "Demnark", "Denmark ", "Denamrk", "Denark", "Denmarkk",
            "Denmark ", "Demnak", "Denamark", "Demnark ", "Denmakr",
            "Denmarkl", "Denmark;", "Denmzrk", "Denmark "
        ],
        "synonyms": [
            "Danmark",
            "Kingdom of Denmark"
        ],
        "region": "Europe"
    },
    {
        "feature": "France",
        "spelling_variations": [
            "Fcance", "Fracne", "France ", "Frace", "Franch", "Francee",
            "France ", "Fracne ", "Franc", "Francfe", "France ",
            "Framce", "Franfe", "Francee ", "Francre"
        ],
        "synonyms": [
            "République française",
            "République Française",
            "French Republic"
        ],
        "region": "Europe"
    },
    {
        "feature": "India",
        "spelling_variations": [
            "Inida", "Idnia", "Idia", "India ", "Indiaa", "INdia", "Indaia",
            "Indai", "India ", "Indiia", "INdia ", "Indida", "Indiia ",
            "India ;", "Indiam"
        ],
        "synonyms": [
            "Bharat",
            "Republic of India"
        ],
        "region": "Asia"
    }
]

# This file contains a dictionary of furniture styles with synonyms and spelling variations.
STYLE_DICTIONARY = [
    {
        "feature": "Rustic",
        "spelling_variations": [
            "Rustc", "Rustik", "Rustick", "Ristic", "Rucsic", "Rustix", "Rustci", 
            "Ruatic", "Rustiv", "Rustiec", "Rustoc", "Rustica", "Rusticc", 
            "Russtic", "Rustuc"
        ],
        "synonyms": [
            "country", "cottage", "farmhouse", "rural",
            "woodland", "barnyard", "cabin"
        ]
    },
    {
        "feature": "Contemporary",
        "spelling_variations": [
            "Cotemporary", "Contempory", "Contemporay", "Contemporry", "Contemporaray", 
            "Contemprary", "Contermporary", "Contamporary", "Contentporary", 
            "Contemporarty", "Contemperary", "Contemparary", "Contemporyy", 
            "Contemporaryy", "Contemporaru"
        ],
        "synonyms": [
            "current", "up-to-date", "cutting-edge", "present-day",
            "state-of-the-art", "avant-garde"
        ]
    },
    {
        "feature": "Mid-Century",
        "spelling_variations": [
            "MidCentury", "Mid Centry", "Mid-Centry", "Mid-Cetury", "Mid-Centruy", 
            "Mid-Centuray", "Md-Century", "Mid-Centryy", "Mid-Cnetury", 
            "Mid-Dentury", "Mid-Vcentury", "Mid-CEntury", "Mid-Centuryy", 
            "MId-Century", "Mid - Century"
        ],
        "synonyms": [
            "midcentury modern", "MCM", "1950s style",
            "post-war modern", "atomic age"
        ]
    },
    {
        "feature": "Bohemian",
        "spelling_variations": [
            "Bohemain", "Bohemiam", "Bohemien", "Boheiman", "Bohemmian", 
            "Boheimien", "Bohemina", "Bohemien", "Bohemiaan", "Bomemian", 
            "Bohamian", "Bohemainn", "Bohemiane", "Bohemisn", "Bohemiena"
        ],
        "synonyms": [
            "boho", "eclectic", "gypsy",
            "artsy", "free-spirited", "nomadic"
        ]
    },
    {
        "feature": "Minimalistic",
        "spelling_variations": [
            "Mimimalistic", "Minimalstic", "Minamilistic", "Minimalisic", 
            "Minimalisitc", "Minimalisitic", "Minimalistick", "Minmalistic", 
            "Minimallistic", "Minimalistc", "Minimalisti", "Minimalistics", 
            "Minimalsitic", "Minimalistick", "Minimalistuc"
        ],
        "synonyms": [
            "minimalist", "clean", "streamlined",
            "pared-down", "simplicity", "essential"
        ]
    },
    {
        "feature": "Scandinavian",
        "spelling_variations": [
            "Scandanavian", "Scaninavian", "Scandinaviann", "Scandanivan", 
            "Scadinavian", "Sandinavian", "Scandinavain", "Scandanavain", 
            "Scanfianvian", "Scandinavian ", "Scaninavain", "Scandanivin", 
            "Scandianvian", "Scandanavien", "Scandinavianm"
        ],
        "synonyms": [
            "Scandi", "Nordic", "Scando", "Danish modern",
            "Finnish style", "Swedish design"
        ]
    },
    {
        "feature": "Art Deco",
        "spelling_variations": [
            "Artdeco", "Artdco", "Art Dec", "Art Decoe", "Art Deko", "Art Deco ", 
            "Art-Deco", "ArtDecoe", "Art DEco", "Atr Deco", "Art Deo", 
            "Art Dexo", "Art dEco", "Art Deco o", "Art Dco"
        ],
        "synonyms": [
            "jazz age", "machine age", "streamline moderne",
            "Deco", "20s glamour", "Roaring Twenties style"
        ]
    },
    {
        "feature": "Classical",
        "spelling_variations": [
            "Classcial", "Classiccal", "CLassical", "Clasical", "Classial", 
            "Classicla", "Claasical", "Classsical", "Classicul", "Classciall", 
            "Classicla ", "Classikal", "Classycal", "Classical ", "Classcical"
        ],
        "synonyms": [
            "traditional", "timeless", "formal",
            "historical", "elegant", "academical"
        ]
    },
    {
        "feature": "NeoClassic",
        "spelling_variations": [
            "Neo Classic", "Neo-Classic", "Neoclassic", "NeoClasic", "Neoclassic", 
            "NeoClassicc", "NeoClasic", "NeoClassic ", "Neo-Classic ", "NeoClasick", 
            "Neo Klassic", "Neoclassic", "NeoCLassic", "NeoClassicl", "NeoClasssic"
        ],
        "synonyms": [
            "neoclassical", "revival", "Empire style",
            "classical revival", "18th-century style"
        ]
    },
    {
        "feature": "Modern",
        "spelling_variations": [
            "MOdern", "Modren", "Moden", "Moder", "Mordern", "Modernn", 
            "Moderrn", "Modern ", "Modernn ", "Moderm", "Mdern", 
            "Moderbn", "Modermn", "Mordernn", "Mofern"
        ],
        "synonyms": [
            "present-day", "state-of-the-art",
            "up-to-the-minute", "new-fangled"
        ]
    },
    {
        "feature": "Industrial",
        "spelling_variations": [
            "Industiral", "Idustrial", "Industrail", "Indutrial", "Industrail ", 
            "Industrial ", "Industrual", "Industrail ", "Industrial ", "Industriall", 
            "Industiral ", "Industrail ", "IndustrialL", "Industrialm", "Industrual"
        ],
        "synonyms": [
            "factory", "warehouse", "urban loft",
            "raw", "mechanical"
        ]
    }
]

VARIANT_FEATURES = {
    "1 Seater": ["1 seater", "single seater", "one seater"],
    "2 Seater": ["2 seater", "two seater", "double seater", "loveseat"],
    "3 Seater": ["3 seater", "three seater", "seat 3", "3 people", "triple seater"],
    "4 Seater": ["4 seater", "four seater", "seat 4"],
    "5 Seater": ["5 seater", "five seater", "seat 5"],
}

FEATURE_DICTIONARY = {
  "Metal Legs":
    [
        "steel legs",
        "aluminum supports",
        "iron base",
        "metallic feet",
        "chrome legs",
        "brass legs",
        "stainless steel legs",
        "industrial legs",
        "bronze legs",
        "metal supports",
        "metal pedestals",
        "contemporary metal legs",
        "metal stilts",
        "aluminum frame legs",
        "metal rod legs",
        "brushed metal legs",
        "iron feet",
        "metal tube legs",
        "metal hairpin legs",
        "steel base",
        "metal framework legs",
        "metallic support structure",
        "metal spindle legs",
        "alloy legs",
        "metal foundation"
    ],
    "Continuous Structure":
    [
        "single-piece design",
        "seamless structure",
        "uninterrupted frame",
        "all-in-one construction",
        "unified body",
        "flowing form",
        "one-piece design",
        "integrated frame",
        "solid structure",
        "contiguous form",
        "seamless body",
        "monolithic structure",
        "unbroken frame",
        "cohesive design",
        "uniform structure",
        "connected elements",
        "joined construction",
        "integral design",
        "unified framework",
        "unsegmented structure",
        "uninterrupted silhouette",
        "fused components",
        "non-sectional design",
        "streamlined structure",
        "harmonious frame"
    ],
    "With Armrest":
    [
        "arm support",
        "side rests",
        "arm guards",
        "elbow rests",
        "side supports",
        "arm platforms",
        "armrests included",
        "hand rests",
        "armrest equipped",
        "arm braces",
        "forearm rests",
        "arm holders",
        "side arms",
        "arm pads",
        "limb supports",
        "sided support",
        "arm cushions",
        "lateral supports",
        "armed design",
        "arm flanks",
        "comfort arms",
        "arm panels",
        "side extensions",
        "arm barriers",
        "limb rests"
    ],
    "Squared Arms":
    [
        "rectangular arms",
        "right-angled arms",
        "boxy arms",
        "geometric arms",
        "angular arms",
        "straight arms",
        "square-edged arms",
        "block arms",
        "cubic arms",
        "sharp-cornered arms",
        "linear arms",
        "regular arms",
        "box-shaped arms",
        "right-angle supports",
        "flat-top arms",
        "orthogonal arms",
        "quadrilateral arms",
        "rigid arms",
        "perpendicular arms",
        "rectilinear arms",
        "crisp arms",
        "hard-edged arms",
        "cornered arms",
        "clean-lined arms",
        "structured arms"
    ],
    "Upholstered Base":
    [
        "padded base",
        "fabric covered base",
        "cushioned foundation",
        "soft base",
        "textile covered bottom",
        "upholstered platform",
        "padded bottom",
        "fabric base",
        "textile foundation",
        "soft bottom structure",
        "cushioned underside",
        "fabric wrapped base",
        "material covered foundation",
        "textile encased base",
        "lined base",
        "padded plinth",
        "upholstered support",
        "covered base",
        "fabric supported bottom",
        "padded foundation",
        "textile clad base",
        "material adorned platform",
        "cushioned plinth",
        "upholstered underbelly",
        "soft foundation"
    ],
    "Wooden Plinth":
    [
        "timber base",
        "wooden foundation",
        "wood platform",
        "wooden pedestal",
        "hardwood plinth",
        "timber stand",
        "wooden support base",
        "solid wood base",
        "wooden underbody",
        "timber foundation",
        "wooden block base",
        "natural wood base",
        "wooden underside",
        "timber pedestal",
        "wood framework base",
        "wooden footing",
        "timber platform",
        "wooden substructure",
        "wood pediment",
        "timber mounting",
        "wooden podium",
        "natural timber base",
        "wood slab base",
        "wooden foundation block",
        "timber support structure"
    ],
    "Fixed Arms":
    [
        "stationary arms",
        "immovable arms",
        "permanent arms",
        "non-adjustable arms",
        "static arms",
        "anchored arms",
        "secured arms",
        "rigid arms",
        "non-removable arms",
        "stable arms",
        "fixed armrests",
        "integrated arms",
        "attached arms",
        "non-detachable arms",
        "built-in arms",
        "solid arms",
        "permanent armrests",
        "unmovable arms",
        "set arms",
        "fixed side supports",
        "immobile arms",
        "non-moving arms",
        "welded arms",
        "locked arms",
        "stationary armrests"
    ],
    "Chesterfield":
    [
        "button-tufted sofa",
        "deep buttoned sofa",
        "rolled arm sofa",
        "quilted leather sofa",
        "classic tufted couch",
        "traditional buttoned sofa",
        "leather tufted settee",
        "diamond quilted sofa",
        "luxurious buttoned couch",
        "rolled arm tufted sofa",
        "Victorian tufted sofa",
        "classic English sofa",
        "button-back sofa",
        "capitonné sofa",
        "deep buttoned upholstery",
        "gentlemen's club sofa",
        "traditional English couch",
        "scroll arm tufted sofa",
        "leather quilted couch",
        "deep-set button sofa",
        "diamond pattern tufted sofa",
        "formal buttoned sofa",
        "heritage tufted design",
        "classic buttoned chesterfield",
        "studded leather sofa"
    ],
    "Horizontal Tufting":
    [
        "lateral button quilting",
        "sideways diamond stitching",
        "crosswise tufting",
        "transverse buttoning",
        "parallel tufted lines",
        "linear button patterning",
        "row tufting",
        "widthwise stitched pattern",
        "side-to-side quilting",
        "horizontal button detail",
        "lateral channel stitching",
        "cross tufting",
        "transverse quilting",
        "horizontal button quilting",
        "sideways capitonné",
        "linear quilted pattern",
        "across stitching",
        "lateral diamond pattern",
        "breadthwise tufting",
        "horizontal stitch detail",
        "crosswise buttoned pattern",
        "lateral quilted lines",
        "parallel button detail",
        "side-to-side tufted pattern",
        "horizontal channel stitching"
    ],
    "Rectangular Arms":
    [
        "box-style arms",
        "straight-profile arms",
        "right-angled arms",
        "angular arms",
        "flat-panel arms",
        "block arms",
        "rectilinear armrests",
        "angular-profile arms",
        "square-sided arms",
        "panel arms",
        "flat-front arms",
        "tile arms",
        "grid arms",
        "slab arms",
        "frame arms",
        "geometric arms",
        "edge arms",
        "straight-edge arms",
        "paneled arms",
        "modular arms",
        "slotted arms",
        "planar arms",
        "slab-profile arms",
        "box-edged arms",
        "panel-profile arms"
    ],
    "Plain Back Without Division":
    [
        "solid back",
        "undivided back",
        "smooth backrest",
        "one-piece back",
        "flat back",
        "continuous back",
        "seamless backrest",
        "unbroken back",
        "plain backrest",
        "unsegmented back",
        "single-panel back",
        "uniform back",
        "straight backrest",
        "monolithic back",
        "clean-back design",
        "minimalist back",
        "solid-panel back",
        "one-piece backrest",
        "flat-panel back",
        "solid back support",
        "full backrest",
        "undivided backrest",
        "plain panel back",
        "uninterrupted back",
        "slick back"
    ],
    "Low Back":
    [
        "mid-height back",
        "short backrest",
        "low-profile back",
        "low-rise back",
        "reduced back height",
        "compact back",
        "subtle backrest",
        "low-slung back",
        "minimal back",
        "shallow backrest",
        "low-shell back",
        "short-profile back",
        "low-backrest design",
        "low-tier back",
        "lowline back",
        "low-rise backrest",
        "lowback seating",
        "low-support back",
        "low-back frame",
        "dwarf back",
        "grounded back",
        "low-level back",
        "truncated backrest",
        "short-form back",
        "stubby back",
        "LowBack",
        "low-back",
        "low-backrest",
        "short back",
        "low profile back",
        "shallow back",
        "mini backrest",
        "grounded back",
        "diminished back height",
        "compact back",
        "low-back seating"
    ],
    "Piping On Back":
    [
        "back piping",
        "edged back trim",
        "back piping detail",
        "piped backrest",
        "back seam piping",
        "contrast back piping",
        "back edge piping",
        "piping trim on back",
        "back border piping",
        "outline piping back",
        "back seam trim",
        "back piping accent",
        "back welt trim",
        "welded piping back",
        "back welted edge",
        "piped seam back",
        "back cushion piping",
        "back piping line",
        "piped edge backrest",
        "back trim piping",
        "back piping finish",
        "back welt detail",
        "back panel piping",
        "back piping outline"
    ],
    "Grid Tufted Back":
    [
        "square tufted back",
        "paneled tuft back",
        "crisscross back",
        "checker tuft back",
        "quadrant tufting",
        "box tufted back",
        "grid-pattern tufting",
        "matrix tufted back",
        "grid-quilt back",
        "cubic tufted back",
        "panel tufted back",
        "grid-style tufting",
        "block tufted back",
        "grid-knit tufting",
        "grid quilting back",
        "square-channel tufting",
        "check tuft back",
        "grid-backed tuft",
        "paneled quilting",
        "checkerboard tufting",
        "gridset tufting",
        "square-grid tuft back",
        "tri-grid tufted back",
        "gridline tuft back",
        "grid tuft panel"
    ],
    "Flared Arms":
    [
        "splayed arms",
        "winged arms",
        "flared-profile arms",
        "bell arms",
        "trumpet arms",
        "flounce arms",
        "outward arms",
        "flare arms",
        "flared-edge arms",
        "flange arms",
        "flair arms",
        "everted arms",
        "flared-side arms",
        "flared-cut arms",
        "wingback arms",
        "flared-armrests",
        "fluted arms",
        "fluted-profile arms",
        "fluted-edge arms",
        "flared-shell arms",
        "flared-form arms",
        "flared-frame arms",
        "wide-flare arms",
        "flared-bracket arms"
    ],
    "Fabric":
    [
        "textile",
        "cloth",
        "woven material",
        "upholstery fabric",
        "cover material",
        "fabrication",
        "drapery",
        "woven cloth",
        "textile cover",
        "covering fabric",
        "fabric weave",
        "fabric material",
        "upholstery cloth",
        "soft textile",
        "lining fabric",
        "fabric covering",
        "twill",
        "velvet",
        "chenille",
        "microfiber",
        "leatherette",
        "suede",
        "canvas",
        "jacquard",
        "felt",
        "mesh",
        "faux leather"
    ],
    "Flat Arms":
    [
        "slab arms",
        "panel arms",
        "flat-profile arms",
        "planar arms",
        "slab-profile armrests",
        "flat-panel arms",
        "board arms",
        "plank arms",
        "flat-edge arms",
        "sheet arms",
        "flat-top arms",
        "flat-surface arms",
        "tray arms",
        "flat-section arms",
        "panel-cut arms",
        "flat slab arms",
        "flatboard arms",
        "panel-profile arms",
        "flat-form arms",
        "flatplane arms",
        "flatrest arms",
        "slabrest arms",
        "flat-module arms",
        "flatblock arms",
        "flatbeam arms"
    ],
    "Bean":
    [
        "bean bag",
        "bean-shaped cushion",
        "bean ottoman",
        "bean pouf",
        "bean seating",
        "bean pod",
        "bean-style seat",
        "bean pillow",
        "bean-form cushion",
        "bean module",
        "bean furniture",
        "bean rest",
        "bean chair",
        "bean lounger",
        "bean stool",
        "bean cushion",
        "bean sack seat",
        "bean pad",
        "bean pouch",
        "bean block",
        "bean block seat",
        "bean foam seat",
        "bean case",
        "bean shell",
        "bean unit"
    ],
    "Split Seat":
    [
        "dual-seat cushion",
        "divided seat",
        "split-cushion seat",
        "bilevel seat",
        "two-part seat",
        "segmented seat",
        "split-cushion",
        "paired seat",
        "twin-seat cushion",
        "split-pad seat",
        "split bench",
        "split-pad cushion",
        "bisected seat",
        "double-cushion seat",
        "two-piece seat",
        "split foam seat",
        "split upholstered seat",
        "split-seat design",
        "dual-cushion seat",
        "saddle seat",
        "split-surface seat",
        "divided cushion",
        "split-rest seat",
        "two-section seat",
        "split-panel seat"
    ],
    "Braid Piping":
    [
        "braided trim",
        "corded piping",
        "rope-edge trim",
        "braid welt",
        "braided welt",
        "cord welting",
        "rope piping",
        "braid edge accent",
        "braided border trim",
        "corded welt",
        "twisted piping",
        "plaited piping",
        "braid detailing",
        "rope-edge piping",
        "braid seam finish",
        "braided seam piping",
        "cord edge trim",
        "rope welt detail",
        "braided cushion piping",
        "corded edge piping",
        "braid welt accent",
        "twisted cord trim",
        "braided join trim",
        "rope join piping",
        "plaited seam trim",
        "braided piping accent"
    ],
    "Non-Uniform Seat Division":
    [
        "irregular seat segmentation",
        "uneven cushion split",
        "asymmetrical seat division",
        "random seat panels",
        "staggered seat sections",
        "offset cushion divisions",
        "inconsistent seat split",
        "multi-size seat panels",
        "varied seat modules",
        "non-symmetrical seat blocks",
        "unequal seat segments",
        "patchwork seat design",
        "asym seat layout",
        "jigsaw seat pattern",
        "mixed-size seat divisions",
        "broken-line seat split",
        "ragged seat segmentation",
        "interrupted seat division",
        "nonlinear seat panels",
        "uneven bench split",
        "asymmetric cushion segmentation",
        "off-kilter seat split",
        "erratic seat division",
        "randomized seat sections",
        "unequal panel seating"
    ],
    "Metal Wire Frame":
    [
        "wireframe structure",
        "metal rod frame",
        "wire-supported frame",
        "rod-wire chassis",
        "metal grid frame",
        "wire mesh frame",
        "metal wire chassis",
        "wire skeleton",
        "wire armature",
        "rod-and-wire frame",
        "wire cage frame",
        "metal strand frame",
        "wire grid support",
        "rod frame network",
        "wire bracing frame",
        "metal filament frame",
        "wire lattice frame",
        "tubular wire frame",
        "wire structural frame",
        "metal wire support",
        "wire armature frame",
        "wireframe base",
        "rod-wire support",
        "metal wire network",
        "wire chassis frame",
        "wirework frame"
    ],
    "Curved":
    [
        "arched",
        "bowed",
        "arched-profile",
        "radius",
        "arc-shaped",
        "swept-back",
        "elliptical",
        "crescent",
        "convex",
        "concave",
        "flexed",
        "c-shaped",
        "sinuous",
        "rounded-form",
        "undulating",
        "wave-like",
        "fluid profile",
        "curvature",
        "arched silhouette",
        "arched contour",
        "curvilinear",
        "bent",
        "looped",
        "arched-frame",
        "curved-edge",
        "organic curve"
    ],
    "Upholstered Shell":
    [
        "padded shell",
        "cushioned shell",
        "fabric-clad shell",
        "upholstery shell",
        "softshell frame",
        "upholstered body",
        "padded frame shell",
        "cushioned housing",
        "upholstered casing",
        "padded enclosure",
        "textile shell",
        "quilted shell",
        "padded carcass",
        "upholstered cover",
        "fabric shell",
        "cushioned frame",
        "upholstered chassis",
        "soft-shell upholstery",
        "padded shell housing",
        "upholstered shell structure",
        "cushioned shell frame",
        "upholstered framework",
        "padded cover shell",
        "fabric-clad housing",
        "textile-clad shell"
    ],
    "Armrest Height Aligned with Backrest":
    [
        "arm level with back",
        "flush armrest",
        "armrest-backrest flush",
        "arm-back alignment",
        "arms even with back",
        "armrest levelback",
        "aligned armrests",
        "arm-backrest level",
        "armrest flush to back",
        "armrest-backrest level",
        "arms inline with back",
        "arm-back flush design",
        "level armrest",
        "arm-backrest alignment",
        "arm’s height flush back",
        "armrest matched back height",
        "armrest and back aligned",
        "armrest-backrest parallel",
        "backrest-armrest level",
        "armrest at back height",
        "arm-backrest coordination",
        "armrest even-back",
        "aligned arm and backrest",
        "arm-backrest sync",
        "armrest-back sync"
    ],
    "Leather Back Covering":
    [
        "leather-wrapped back",
        "leather-clad backrest",
        "back leather upholstery",
        "leather-backed rest",
        "back covered in leather",
        "leather panel back",
        "full leather back",
        "leather sheathed backrest",
        "backrest in leather",
        "leather finish back",
        "leather-lined back",
        "leather back panel",
        "back leather casing",
        "leather-clad support",
        "leather back cover",
        "backrest leather sheath",
        "leather skinned back",
        "leather back overlay",
        "leatherback design",
        "back leather wrap",
        "leather rear panel",
        "rear leather backrest",
        "smooth leather back",
        "premium leather back",
        "leather-draped back"
    ],
    "Rounded Arms":
    [
        "curved armrests",
        "circular-profile arms",
        "oval arms",
        "arched arms",
        "bulbous arms",
        "tubular arms",
        "pillowed arms",
        "barrel arms",
        "radius-edge arms",
        "looped arms",
        "semicircular arms",
        "arch-profile arms",
        "egg-shaped arms",
        "contoured arms",
        "soft-radius arms",
        "round-top arms",
        "smooth-curve arms",
        "pod arms",
        "curve-edge arms",
        "bulging arms",
        "rounded-edge arms",
        "reclined curve arms",
        "bean-shaped arms",
        "arched-edge arms",
        "rounded-shell arms",
        "curved arms",
        "arched arms",
        "circular arms",
        "oval arms",
        "swept arms",
        "bowed arms",
        "contoured arms",
        "tubular arms",
        "radius arms",
        "semi-circular arms",
        "roundedArms",
        "circular arms",
        "smooth arms",
        "contoured arms",
        "arched arms",
        "soft-edged arms",
        "curved armrests",
        "rounded support",
        "crescent arms",
        "dome-shaped arms",
        "bulbous arms",
        "sculpted arms",
        "oval arms",
        "round-top arms",
        "curvaceous arms",
        "flowing arms",
        "smoothly contoured arms",
        "semi-circular arms",
        "gentle curve arms",
        "roll arms",
        "cylindrical arms",
        "spherical arms",
        "fluid-shaped arms",
        "arc-shaped arms",
        "undulating arms"
    ],
    "Sinuous Curve Arms":
    [
        "wavy arms",
        "s-shaped arms",
        "undulating armrests",
        "flowing curve arms",
        "sinuous-profile arms",
        "ribbon-like arms",
        "meandering arms",
        "serpentine arms",
        "s-curve arms",
        "swooping arms",
        "snake-line arms",
        "ripple arms",
        "wave-form arms",
        "curvy arms",
        "sinusoidal arms",
        "sweeping curve arms",
        "squiggle arms",
        "ribbon-profile arms",
        "sinuous-edge arms",
        "meander arms",
        "twist curve arms",
        "flow-line arms",
        "graceful curve arms",
        "flowing-profile arms",
        "undulate arms"
    ],
    "Mid Back":
    [
        "medium-height backrest",
        "mid-height back",
        "mid-profile back",
        "mid-rise backrest",
        "moderate back height",
        "average backrest",
        "midline back",
        "mid-tier back",
        "mid-back support",
        "midlevel backrest",
        "intermediate back",
        "midrise back",
        "mid-level backrest",
        "midway backrest",
        "mid back frame",
        "mid-back design",
        "mid-height support",
        "mid-stack backrest",
        "mid-section back",
        "mid-backrest height",
        "mid-profile support",
        "midback seating",
        "mid-shell back",
        "midback frame",
        "midback panel"
    ],
    "Cylindrical Back":
    [
        "round backrest",
        "barrel back",
        "tube-shaped back",
        "tube backrest",
        "drum back",
        "roller back",
        "circular-profile back",
        "column back",
        "pipe backrest",
        "cylinder back"
    ],
    "Organic Shape":
    [
        "natural form",
        "fluid shape",
        "curvilinear form",
        "biomorphic shape",
        "freeform contour",
        "naturalistic silhouette",
        "flowing shape",
        "biomorphic curve",
        "undulating form",
        "organic contour"
    ],
    "Armrest Integrated With Structure":
    [
        "built-in armrests",
        "structural arm support",
        "armrests as frame",
        "integral arms",
        "frame-integrated arms",
        "one-piece arms",
        "arm-frame fusion",
        "monolithic arms",
        "armrest-frame merge",
        "armrest-struct fusion"
    ],
    "Sinuous":
    [
        "wavy",
        "undulating",
        "curvy",
        "serpentine",
        "flowing",
        "meandering",
        "ribbon like",
        "s shaped",
        "sweeping",
        "gracefully curved"
    ],
    "Metal Plinth":
    [
        "metal base",
        "steel plinth",
        "metal pedestal",
        "metal platform",
        "metal footing",
        "iron plinth",
        "aluminum plinth",
        "metal dais",
        "metal riser",
        "metal sub-base"
    ],
    "With Optional Loose Cushions":
    [
        "with cushions",
        "with loose cushions",
        "optional cushions",
        "detachable cushions",
        "removable cushions",
        "cushions included",
        "with add-on cushions",
        "optional throw cushions",
        "with free cushions",
        "cushions on demand",
        "loose-pillow option",
        "loose cushions",
        "back cushions"
    ],
    "Flared High Back":
    [
        "splayed high back",
        "winged high back",
        "bell-top back",
        "trumpet high back",
        "flounce high back",
        "everted high back",
        "flared-tall back",
        "wide high back",
        "bell-shaped back",
        "flared tall back"
    ],
    "Slanted Legs": ["slanted legs", "angled legs", "sloping legs"],
    "Sloping Arms":
    [
        "angled arms",
        "inclined arms",
        "raked arms",
        "leaning arms",
        "tilted arms",
        "slanted arms",
        "battered arms",
        "eased arms",
        "sloped armrests",
        "gradient arms"
    ],
    "Tubular Hollow Wooden Frame":
    [
        "hollow tube wood frame",
        "tubular timber frame",
        "wooden tube chassis",
        "tube-structured wood",
        "hollow-wood tubing",
        "wood tubular skeleton",
        "timber tube frame",
        "cored wood tube frame",
        "pipe-like wood frame",
        "tubular wood support"
    ],
    "Pleated Back":
    [
        "folded backrest",
        "gathered back",
        "pleat-detail back",
        "pinched-back",
        "accordion back",
        "tucked backrest",
        "pleated panel back",
        "ruched back",
        "pleat-pattern back",
        "pleat-trimmed back"
    ],
    "Angular Back":
    [
        "angled backrest",
        "geometric back",
        "faceted back",
        "sharp-back",
        "polygonal back",
        "triangular backrest",
        "edged back",
        "cornered back",
        "angular-profile back",
        "straight-angle back"
    ],
    "Folded Arms":
    [
        "pleated arms",
        "crease arms",
        "tucked arms",
        "fold-detail arms",
        "pinched arms",
        "wrapped arms",
        "overlay arms",
        "gathered arms",
        "origami-style arms",
        "fold-pattern arms"
    ],
    "Heavy Base":
    [
        "solid base",
        "massive foundation",
        "weighted base",
        "substantial base",
        "sturdy base",
        "dense base",
        "robust foundation",
        "bulky base",
        "hefty base",
        "substantial plinth"
    ],
    "Sleek Arms":
    [
        "slim arms",
        "streamlined arms",
        "svelte arms",
        "elegant arms",
        "smooth arms",
        "sleek-profile arms",
        "thin arms",
        "polished arms",
        "refined arms",
        "shapely arms"
    ],
    "Straight Legs":
    [
        "linear legs",
        "upright legs",
        "vertical legs",
        "plumb legs",
        "right-angle legs",
        "unbent legs",
        "direct legs",
        "straight-profile legs",
        "flush legs",
        "even legs"
    ],
    "Planar Legs":[
        "flat legs",
        "slab legs",
        "panel legs",
        "plate legs",
        "planed legs",
        "sheet legs",
        "plane legs",
        "planed-profile legs",
        "plank legs",
        "planar-profile legs"
    ],
    "Adjustable Back":
    [
        "reclinable backrest",
        "tilt-back",
        "movable back",
        "adjustable tilt back",
        "height-adjust back",
        "flexible backrest",
        "modular back",
        "variable back angle",
        "pivot backrest",
        "customizable back"
    ],
    "Integrated Arms & Legs":
    [
        "one-piece arms and legs",
        "unified supports",
        "monoblock frame",
        "integral limbs",
        "combined arms-legs",
        "arms-legs fusion",
        "joined arms and legs",
        "all-in-one supports",
        "fusion frame",
        "continuous limbs"
    ],
    "Upholstered Structure":
    [
        "padded framework",
        "cushioned structure",
        "fabric-clad frame",
        "upholstery frame",
        "soft-shell structure",
        "padded skeleton",
        "textile frame",
        "upholstered chassis",
        "cushioned skeleton",
        "fabric-wrapped frame"
    ],
    "Arms With Metal Detail":
    [
        "metal-trim arms",
        "arms with metal accents",
        "metal-detailed arms",
        "arms with metal inlay",
        "metallined arms",
        "arms with metal trim",
        "metal-embellished arms",
        "arms with metal edging",
        "arms with metal finish",
        "arms with metal highlights"
    ],
    "Leather Piping":
    [
        "leather welting",
        "leather trim",
        "leather-bound piping",
        "leather-edged seam",
        "leather accent piping",
        "leather cord trim",
        "leather welt",
        "leather seam piping",
        "leather border piping",
        "leather outline trim"
    ],
    "Metal Detail":
    [
        "metal accent",
        "metallic trim",
        "metal embellishment",
        "metal highlight",
        "metal ornament",
        "metal inlay",
        "metal edging",
        "metal applique",
        "metal  feature",
        "metal decorative element"
    ],
    "LShape":
    [
        "L-shaped",
        "angle-shaped",
        "corner form",
        "right-angle profile",
        "L-profile",
        "L-configuration",
        "corner sectional",
        "elbow shape",
        "L-configuration frame",
        "L-structure"
    ],
    "Without Armrest":
    [
        "armless",
        "no armrests",
        "open sides",
        "arm-free design",
        "armless profile",
        "no-side supports",
        "don't have arms",
        "no arm support",
        "without arms",
        "no arms",
        "arm-void",
        "armrest-less",
        "sans armrests"
    ],
    "Modular Arm":
    [
        "detachable arm",
        "interchangeable armrest",
        "reconfigurable arm",
        "modular armrest",
        "arm module",
        "slot-in arm",
        "arm component",
        "arm unit",
        "add-on armrest",
        "swap-out arm"
    ],
    "Piping Follows Structure":
    [
        "contour piping",
        "profile-tracing piping",
        "structure-lined piping",
        "outline piping",
        "form-fitting piping",
        "edge-mapped piping",
        "architecture-aligned piping",
        "frame-conforming piping",
        "shape-tracing welt",
        "structure-hugging piping"
    ],
    "Metal Structure":
    [
        "metal frame",
        "metal chassis",
        "steel structure",
        "iron framework",
        "aluminum skeleton",
        "metal substructure",
        "metal build",
        "steel framework",
        "metal body",
        "metal support frame"
    ],
    "Splayed Arms":
    [
        "flared arms",
        "splayed-profile arms",
        "winged arms",
        "outward-leaning arms",
        "bell arms",
        "trumpet arms",
        "everted arms",
        "flounce arms",
        "flared-edge arms",
        "splayed-armrests"
    ],
    "Quilted Back":
    [
        "tufted back",
        "diamond-quilt back",
        "panel-quilt back",
        "channel-quilt back",
        "padded quilt back",
        "quilted-panel back",
        "stitched quilt back",
        "cushioned quilt back",
        "grid-quilt back",
        "box-quilt back"
    ],
    "Upholstered Plinth":
    [
        "padded plinth",
        "cushioned base plinth",
        "fabric-covered plinth",
        "upholstery plinth",
        "textile plinth",
        "soft plinth",
        "upholstered pedestal",
        "padded pedestal",
        "cushioned plinth",
        "upholstered sub-base"
    ],
    "Flat Piping":
    [
        "slim welt",
        "flat welt trim",
        "flat seam piping",
        "low-profile piping",
        "flat-edge piping",
        "tape piping",
        "flat binding",
        "flat seam trim",
        "flush piping",
        "flat border piping"
    ],
    "Floor Length Arms":
    [
        "full-drop arms",
        "floor-to-arm arms",
        "floor-reaching arms",
        "floor-sweeping arms",
        "long arms",
        "floor-touch arms",
        "floor-base arms",
        "ground-length arms",
        "floor-contact arms",
        "floor-hugging arms"
    ],
    "High Back":
    [
        "high-back",
        "tall backrest",
        "lofted back",
        "elevated back",
        "tower back",
        "skyline back",
        "raised backrest",
        "extended back",
        "soaring backrest",
        "lofty back"
    ],
    "Wing Back Design":
    [
        "winged back",
        "batwing back",
        "ear-back design",
        "wingback",
        "paired-wing back",
        "flared-wing back",
        "side-wing back",
        "cradle back",
        "winged headrest",
        "wing-backrest"
    ],
    "Curvilinear Back":
    [
        "sinuous back",
        "curved-profile back",
        "wavy backrest",
        "undulating back",
        "flowing back",
        "organic back",
        "meandering back",
        "arc backrest",
        "ribbon back",
        "curved contour back"
    ],
    "Polyurethane":
    [
        "PU foam",
        "urethane",
        "poly foam",
        "polymer foam",
        "PU material",
        "flexible foam",
        "rigid foam",
        "polymer cushioning",
        "poly-foam",
        "PU upholstery"
    ],
    "Back Cushions Integral To Sofa":
    [
        "sofa-integral back cushions",
        "built-in sofa cushions",
        "sofa-fixed back cushions",
        "one-piece sofa cushions",
        "attached sofa cushions",
        "inbuilt sofa cushions",
        "sofa seam-back cushions",
        "monolithic sofa cushions",
        "sofa cushion–integral back",
        "permanent sofa cushions"
        "integral back cushions",
        "built-in back cushions",
        "fixed back cushions",
        "one-piece back cushions",
        "attached back cushions",
        "inbuilt back cushions",
        "seamless back cushions",
        "monolithic back cushions",
        "cushion-integrated back",
        "permanent back cushions"
    ],
    "External Metal Embellishments":
    [
        "metal studs",
        "rivets",
        "metallic appliques",
        "metal accents",
        "metal trims",
        "metal inlays",
        "metal overlays",
        "metal filigree",
        "metal motifs",
        "metal rosettes",
        "external metal trims",
        "external metallic accents",
        "metal corner caps",
        "metal corner protectors",
        "architectural metal accents",
        "metal leaf embellishments",
        "metal banding",
        "metal stud trim",
        "exposed metalwork",
        "visible metalwork",
        "decorative metal straps",
        "metal bracket embellishments",
        "metal edge trim",
        "metal strap accents",
        "metal panel detailing"
    ],
    "Pebble":
    [
        "pebble shape",
        "pebble-like",
        "pebble pattern",
        "pebble motif",
        "pebble-textured",
        "pebble finish",
        "pebble form",
        "pebble profile",
        "pebble silhouette",
        "pebble contour",
        "pebble surface",
        "pebble effect",
        "pebble-inspired",
        "stone-like",
        "pebblegrain texture",
        "pebblegrain finish",
        "pebblegrain motif",
        "pebblegrain pattern",
        "round pebble form",
        "oval pebble outline",
        "pebble cushion style",
        "pebble ottoman shape",
        "pebble pouf design",
        "pebble-edge detailing",
        "pebbleback style"
    ],
    "Nail Trimming And Nail Buttons":
    [
        "nailhead trim",
        "studded trim",
        "nailhead studs",
        "nailhead accents",
        "stud trim",
        "tack trim",
        "nailhead edging",
        "nailhead border",
        "nailhead detailing",
        "nail-head trim",
        "metal stud trimming",
        "upholstery nails",
        "upholstery tacks",
        "nail-head studs",
        "tack buttons",
        "decorative tacks",
        "button nails",
        "nailhead applique",
        "nailhead pattern",
        "tack border",
        "brass nail trim",
        "nickel nail trim",
        "silver nail trim",
        "antique nail trim",
        "colored nail trim"
    ],
    "Optional Quilted Loose Cushions":
    [
        "optional quilted cushions",
        "optional loose quilted cushions",
        "detachable quilted cushions",
        "removable quilted cushions",
        "quilted throw cushions",
        "quilted loose pillows",
        "quilted cushion inserts",
        "quilted pillow options",
        "loose quilted pillows",
        "add-on quilted cushions",
        "quilted cushion modules",
        "quilted pillow extras",
        "quilted cushioned throws",
        "loose quilt cushions",
        "quilted bolsters",
        "quilted scatter cushions",
        "optional quilt pillows",
        "quilted accent pillows",
        "quilted soft cushions",
        "quilted pad options",
        "quilted comfort cushions",
        "quilted fill pillows",
        "quilted topper cushions",
        "quilted cushion add-ons",
        "quilted cushion pack"
    ],
    "Circular":
    [
        "round",
        "circular profile",
        "ring-shaped",
        "orbicular",
        "disc-like",
        "circle-shaped",
        "radial form",
        "concentric profile",
        "circular silhouette",
        "circular contour",
        "circular frame",
        "circular motif",
        "circular design",
        "circular outline",
        "circular pattern",
        "circular edge",
        "donut-shaped",
        "circular geometry",
        "circular element",
        "circular seat",
        "circular back",
        "circular armrest",
        "circular base",
        "circular feet",
        "circular panel"
    ],
    "Curved Back":
    [
        "contoured backrest",
        "curved-profile back",
        "serpentine backrest",
        "convex back",
        "concave back",
        "radius back",
        "flowing back",
        "bowback",
        "barrelback",
        "wavy back",
        "curved contour back",
        "curved-shell back",
        "ergonomic back",
        "curved-form back",
        "curved silhouette",
        "enveloping back",
        "wrap-back",
        "cradle backrest",
        "curved support",
        "curved upholstered back",
        "smooth curved back",
        "curved ergonomic profile",
        "curved wooden back",
        "curved metal back"
    ],
    "Rounded Back":
    [
        "curved backrest",
        "roll-back",
        "barrel back",
        "bulbous back",
        "arched backrest",
        "circular back",
        "contoured back",
        "rounded-profile back",
        "smooth back",
        "pillowed back",
        "enveloping back",
        "cloud back",
        "padback",
        "tub-back",
        "organic back",
        "radius backrest",
        "ergonomic back",
        "loop-back",
        "scoop-back",
        "archback",
        "looped backrest",
        "barrel-shaped back",
        "rounded silhouette",
        "bubble-back",
        "dome-back"
    ],
    "Dual Tone":
    [
        "two-tone",
        "bi-color",
        "dual-color",
        "two-colour",
        "bi-tone",
        "two-shade",
        "dual-shade",
        "contrast-tone",
        "two-tone finish",
        "dual-hue",
        "twin-tone",
        "two-tone palette",
        "two-tone upholstery",
        "bi-color trim",
        "two-tone piping",
        "two-tone stitching",
        "two-tone surface",
        "two-tone pattern",
        "dual-tone design",
        "two-tone detail",
        "two-tone motif",
        "twin-color",
        "twin-shade",
        "bicolor",
        "duotone"
    ],
    "Two Tone Piping":
    [
        "bi-color piping",
        "dual-color piping",
        "two-tone welting",
        "two-tone trim",
        "contrast piping",
        "bicolor piping",
        "twin-tone piping",
        "dual-tone welt",
        "split-tone piping",
        "two-tone cord",
        "two-tone border",
        "two-tone outline",
        "two-tone seam",
        "two-tone cable",
        "two-tone edge",
        "two-tone accent piping",
        "two-tone profile piping",
        "two-tone stitch",
        "two-tone braiding",
        "two-tone seaming",
        "two-tone welt trim",
        "two-tone braid",
        "dual-tone piping",
        "bi-tone piping",
        "twin-color piping"
    ],
    "CShape":
    [
        "C-shaped",
        "c-profile",
        "C-form",
        "c-curved",
        "C-contour",
        "C-profile frame",
        "c-frame",
        "c-curve",
        "c-back",
        "c-arm",
        "c-leg",
        "c-seat",
        "C-structure",
        "C-motif",
        "c-silhouette",
        "c-arch",
        "C-shape design",
        "c-architecture",
        "c-section",
        "c-shape frame",
        "c-shaped silhouette",
        "c-frame structure",
        "c-moulding",
        "c-edge",
        "c-outline"
    ],
    "Elevated Arms":
    [
        "raised arms",
        "high arms",
        "lifted armrests",
        "elevated armrests",
        "upraised arms",
        "elevated-profile arms",
        "armrests on risers",
        "elevated-side supports",
        "high-position arms",
        "armrests at height",
        "tall arms",
        "elevated-edge arms",
        "raised-side arms",
        "elevated-frame arms",
        "lifted-profile arms",
        "raised-support arms",
        "high-set arms",
        "elevated bracket arms",
        "elevated mount arms",
        "uplifted arms",
        "elevated structure arms",
        "elevated-platform arms",
        "elevated skeleton arms",
        "elevated chassis arms",
        "armrests on stilts"
    ],
    "Leather":
    [
        "hide upholstery",
        "leatherette",
        "genuine leather",
        "aniline leather",
        "top-grain leather",
        "full-grain leather",
        "bonded leather",
        "PU leather",
        "faux leather",
        "eco-leather",
        "nappa leather",
        "suede leather",
        "nubuck leather",
        "corrected-grain leather",
        "split leather",
        "leather finish",
        "leather covering",
        "leather material",
        "leather textile",
        "leather surface",
        "leather skin",
        "leather hide",
        "leather wrap",
        "leather cladding",
        "leather trim"
    ],
    "Grid Tufted Arms":
    [
        "paneled tufted arms",
        "square tuft arms",
        "box tuft arms",
        "grid-pattern armrest",
        "matrix tuft arms",
        "checker tuft arms",
        "cubic tuft arms",
        "grid-quilted arms",
        "panel-quilt arms",
        "block tuft arms",
        "grid-quilt armrests",
        "square-channel arms",
        "gridset tuft arms",
        "gridline tuft arms",
        "gridback arms",
        "panel-tuft arms",
        "checkerboard arms",
        "geometric tuft arms",
        "grid stitch arms",
        "grid-stitched arms",
        "grid-quilt profile arms",
        "grid-lattice arms",
        "grid-section arms",
        "grid-panel arms",
        "grid-quilt overlay arms"
    ],
    "Quilted Arms":
    [
        "tufted arms",
        "diamond-quilt arms",
        "channel-quilt arms",
        "panel-quilt arms",
        "cushioned quilt arms",
        "quilted-panel arms",
        "stitched quilt arms",
        "grid-quilt arms",
        "box-quilt arms",
        "pin-tuck arms",
        "ruched quilt arms",
        "pleated quilt arms",
        "piped quilt arms",
        "quilting-detail arms",
        "padded-quilt arms",
        "buffered quilt arms",
        "quilted-edge arms",
        "quilt-pattern arms",
        "quilt-stitched arms",
        "quilted-overlay arms",
        "cable-quilt arms",
        "ribbon-quilt arms",
        "flanged-quilt arms",
        "ribbed-quilt arms",
        "soft-quilt arms"
    ],
    "Wooden Legs":
    [
        "wooden legs",
        "wooden slanted legs",
        "timber legs",
        "wood legs",
        "solid wood legs",
        "oak legs",
        "walnut legs",
        "maple legs",
        "beech legs",
        "ash legs",
        "birch legs",
        "wooden posts",
        "wooden uprights",
        "wood pillars",
        "wooden stilts",
        "wood pegs",
        "wood struts",
        "wooden supports",
        "wooden columns",
        "wooden shafts",
        "wood beams",
        "wood dowels",
        "wooden feet",
        "wood pedestals",
        "hardwood legs",
        "softwood legs",
        "wood frame legs"
    ],
    "Inclined Seat":
    [
        "sloped seat",
        "angled seat",
        "raked seat",
        "tilted seat",
        "leaning seat",
        "graded seat",
        "eased seat",
        "ramped seat",
        "inclining seat",
        "slope-front seat",
        "bias seat",
        "slanted cushion",
        "inclined-profile seat",
        "sloped-profile seat",
        "tilt-back seat",
        "front-drop seat",
        "rear-rise seat",
        "elevated rear seat",
        "lower front seat",
        "angled-profile seat",
        "graded-profile seat",
        "sloped shell seat",
        "cant seat",
        "cantilevered seat",
        "inclined surface seat"
    ],
    "Metal Frame Arms":
    [
        "metal-structured arms",
        "frame-metal arms",
        "metal chassis arms",
        "steel-frame arms",
        "iron-frame armrests",
        "aluminum-frame arms",
        "metal skeleton arms",
        "metal armature arms",
        "metalwork arms",
        "tubular-frame arms",
        "metal bracket arms",
        "metal rail arms",
        "metal strut arms",
        "wire-frame arms",
        "rod-frame arms",
        "metal beam arms",
        "metal brace arms",
        "metal framework arms",
        "metal profile arms",
        "metal outline arms",
        "structural metal arms",
        "industrial metal arms",
        "architectural arms",
        "metal construction arms",
        "metal grid arms"
    ],
    "Wooden Arms":
    [
        "timber armrests",
        "wood arms",
        "solid wood arms",
        "oak armrests",
        "walnut arms",
        "maple arm supports",
        "beech arms",
        "ash armrests",
        "birch arms",
        "wooden arm modules",
        "wooden arm panels",
        "hardwood arms",
        "softwood arms",
        "wood arm brackets",
        "wood arm frames",
        "wood arm shells",
        "wood arm covers",
        "wood arm mounts",
        "wood arm fittings",
        "wood arm overlays",
        "wood arm trims",
        "wood arm cladding",
        "wood arm detailing",
        "wood arm embellishments",
        "wood arm fillets"
    ],
    "Wooden Base":
    [
        "timber base",
        "wood base",
        "solid wood base",
        "oak base",
        "walnut base",
        "maple base",
        "beech base",
        "ash base",
        "birch base",
        "wood foundation",
        "wooden plinth",
        "wooden pedestal",
        "hardwood base",
        "softwood base",
        "wood slab base",
        "wood block base",
        "wood support base",
        "wood frame base",
        "wood platform",
        "wood chassis base",
        "wood sub-base",
        "wood trim base",
        "wood bed base",
        "wood seating base",
        "wood block support"
    ],
    "Low Armrest":
    [
        "low-profile armrest",
        "short armrest",
        "low-set arms",
        "low-side supports",
        "dropped arms",
        "recessed armrests",
        "low-level arms",
        "low-stage arms",
        "low-mounted arms",
        "low-tier arms",
        "low-rise armrests",
        "stunted arms",
        "stubby arms",
        "grounded arms",
        "mini armrests",
        "compact arms",
        "modest arms",
        "low-grade arms",
        "floor-near arms",
        "semi-recessed arms",
        "under-armrest",
        "low-slung arms",
        "shallow arms",
        "low-profile rests",
        "low station arms"
    ],
    "Planar Base":
    [
        "flat base",
        "planed base",
        "slab base",
        "panel base",
        "plate base",
        "sheet base",
        "plane base",
        "planar-profile base",
        "plank base",
        "flat-profile base",
        "panel-profile base",
        "planar-support base",
        "planar-platform base",
        "planar-frame base",
        "planar-chassis base",
        "planar-structure base",
        "planar-skeleton base",
        "planar-shell base",
        "planar-block base",
        "planar-pedestal base",
        "planar-plinth base",
        "planar-platform",
        "planar-foundation",
        "planar-footing",
        "planar-support"
    ],
    "Asymmetric Back":
    [
        "uneven backrest",
        "off-center back",
        "lopsided back",
        "non-symmetrical back",
        "irregular backrest",
        "asym back",
        "skewed back",
        "bias backrest",
        "one-sided back",
        "asymmetrical backrest",
        "unbalanced back",
        "unequal back panels",
        "asym panel back",
        "irregular-panel back",
        "asym shell back",
        "off-balance back",
        "nonuniform back",
        "asym contour back",
        "asym-profile back",
        "asym silhouette back",
        "asym form back",
        "crooked backrest",
        "twisted back",
        "askew backrest",
        "off-axis back"
    ],
    "Wooden Structure":
    [
        "timber structure",
        "wood framework",
        "wooden frame",
        "timber chassis",
        "wood skeleton",
        "wood substructure",
        "wood build",
        "timber frame",
        "wood support frame",
        "wooden chassis",
        "wood body",
        "wood architecture",
        "wooden shell",
        "wooden skeleton",
        "wood veneered structure",
        "solid wood structure",
        "laminated wood structure",
        "glulam structure",
        "post-and-beam frame",
        "timber-framed structure",
        "wood joint structure",
        "wood stave structure",
        "wood joinery frame",
        "mortise-and-tenon frame",
        "wood truss structure"
    ],
    "Tubular Arms":
    [
        "tube arms",
        "tubular armrests",
        "pipe arms",
        "circular-tube arms",
        "hollow-tube arms",
        "tubing arms",
        "tube-profile arms",
        "tubular-profile arms",
        "pipe-frame arms",
        "tube-frame arms",
        "tubular-support arms",
        "rod arms",
        "bar arms",
        "tube-structure arms",
        "tubular-shell arms",
        "cylindrical arms",
        "round-tube arms",
        "metal-tube arms",
        "tubular-skeleton arms",
        "tube-work arms",
        "tube-motif arms",
        "tubular-outline arms",
        "hollow-rod arms",
        "pipe-outline arms",
        "tubular-chassis arms"
    ],
    "Angular":
    [
        "sharp-edged",
        "angled",
        "geometric",
        "faceted",
        "orthogonal",
        "polygonal",
        "rectilinear",
        "cornered",
        "right-angled",
        "linear",
        "edged",
        "cornered-profile",
        "angled-profile",
        "blocky",
        "chiseled",
        "bevelled",
        "beveled",
        "crisp-edged",
        "triangular",
        "quadrilateral",
        "hexagonal",
        "polygonal-form",
        "angular-contour",
        "angled-silhouette",
        "angular-outline"
    ],
    "Metal Bar Structure Around Back":
    [
        "back metal bar frame",
        "metal surround back",
        "bar-back frame",
        "metal bar backrest",
        "metal hoop back",
        "backrest metal cage",
        "metal rail back support",
        "metal arc back",
        "back metal loop",
        "metal rod back surround",
        "barred back frame",
        "metal-back enclosure",
        "metal-back guard",
        "metal-back railing",
        "metal-back band",
        "metal-back bracket",
        "metal-back arch",
        "back bar chassis",
        "back bar skeleton",
        "metal-back bracketry",
        "metal-back reinforcement",
        "metal-back casting",
        "metal-back cradle",
        "bar-encased back",
        "metal-back trim",
        "metal-back accent"
    ],
    "External Wood Embellishments":
    [
        "wood appliques",
        "wood trims",
        "wood overlays",
        "wood filigree",
        "wood motifs",
        "wood corbels",
        "wood brackets",
        "wood rosettes",
        "wood medallions",
        "wood studs",
        "wood carvings",
        "wood inlays",
        "wood panels",
        "wood ornamentation",
        "wood dentil trim",
        "wood fretwork",
        "wood mouldings",
        "wood scrollwork",
        "wood fillets",
        "wood accents",
        "wood strapwork",
        "wood banding",
        "wood beads",
        "wood keystone",
        "wood fascia",
        "wood cresting"
    ],
    "Plain":
    [
        "simple",
        "unadorned",
        "minimal",
        "clean",
        "bare",
        "smooth",
        "flat",
        "plain-surfaced",
        "undecorated",
        "unembellished",
        "straightforward",
        "basic",
        "elemental",
        "unornamented",
        "no-frills",
        "austere",
        "spartan",
        "barebones",
        "stark",
        "natural",
        "raw",
        "polished",
        "plain-finish",
        "plain-design",
        "plain-style",
        "uncluttered"
    ],
    "Asymmetric Curve":
    [
        "uneven curve",
        "off-center curve",
        "lopsided curve",
        "non-symmetrical curve",
        "irregular curve",
        "skewed curve",
        "bias curve",
        "one-sided curve",
        "asymmetrical curve",
        "crooked curve",
        "twisted curve",
        "askew curve",
        "biased curvature",
        "off-axis curve",
        "unequal curve bend",
        "asym contour",
        "asym-profile curve",
        "uneven bend",
        "nonuniform curve",
        "skewed-profile curve",
        "irregular-contour curve",
        "asym silhouette curve",
        "off-balance curve",
        "crooked-contour",
        "biased-bend"
    ],
    "ContrastPiping":
    [
        "contrast welt",
        "contrast trim piping",
        "contrast cord piping",
        "contrast-edge piping",
        "contrast border piping",
        "contrast welting",
        "contrast seam piping",
        "contrast-color piping",
        "contrast-stitch piping",
        "contrast welt trim",
        "accent piping",
        "highlight piping",
        "outline piping",
        "piping contrast",
        "color-pop piping",
        "edge-highlight piping",
        "border-contrast piping",
        "welt-contrast piping",
        "trim-contrast piping",
        "contrast braid piping",
        "contrast tape piping",
        "contrast piping detail",
        "two-tone piping",
        "contrast seam trim",
        "contrast-cable piping"
    ],
    "Split Back":
    [
        "split back",
        "divided back",
        "back split",
        "split-back design",
        "two-part backrest",
        "dual-panel back",
        "back segmentation",
        "bisected back",
        "back cleft",
        "split back sofa",
        "back division",
        "split-panel back",
        "back bifurcation",
        "split-backrest",
        "back in two sections",
        "backrest split",
        "split-back support",
        "double-back design",
        "back split detail",
        "back seam division",
        "backrest segmentation",
        "two-piece backrest",
        "split-cushion back",
        "split-back cushion",
        "segmented backrest",
        "divided-back cushion",
        "back split motif"
    ],
    "Button Tacked Back":
    [
        "tacked-back buttons",
        "button-tuft backrest",
        "button-backed",
        "button tack tufting",
        "button-studded back",
        "back with tacks",
        "nail-button back",
        "button-brad back",
        "tack-button backrest",
        "button-pin back",
        "button-pin tufting",
        "tacked tuft back",
        "button tack back",
        "studded-back buttons",
        "button tufted back",
        "button tacked upholstery",
        "button-and-tack back",
        "button-studded tuft",
        "back studded with buttons",
        "button tack finish",
        "button-tack detail",
        "pin-back tufting",
        "button-back studs",
        "tack & button back",
        "button-studded upholstery"
    ],
    "Open Back":
    [
        "backless",
        "exposed back",
        "cutaway back",
        "open-backed",
        "back opening",
        "no-back design",
        "rear open frame",
        "back cutout",
        "back gap",
        "back aperture",
        "open rear rest",
        "back void",
        "back notch",
        "back clearance",
        "back recess",
        "open-backrest",
        "rear opening back",
        "back frame only",
        "back skeleton",
        "back lattice",
        "open rear support",
        "back slats open",
        "back frame exposed",
        "open-back frame",
        "back cut-away"
    ],
    "Arched Back":
    [
        "arched back",
        "curved backrest",
        "arched-profile back",
        "bowed back",
        "arc back",
        "arched silhouette",
        "arched-frame back",
        "arch-backed",
        "archback",
        "arched contour",
        "arched shell back",
        "arched-support back",
        "arched-form back",
        "arched-top back",
        "arched panel back",
        "arched cushion back",
        "arched wooden back",
        "arched metal back",
        "arched upholstered back",
        "arched-lattice back",
        "arched-beam back",
        "arched-rib back",
        "arched slat back",
        "arched-grid back",
        "arched lattice back",
        "arched trim back"
    ],
    "Vertical Quilt Pattern":
    [
        "vertical quilting",
        "channel tufting",
        "vertical tuft pattern",
        "vertical stitched channels",
        "row quilting",
        "ribbon tufting",
        "striped quilting",
        "bar quilting",
        "vertical pleating",
        "rail quilting",
        "linear tufting",
        "banded tufting",
        "pipe tufting",
        "vertical-channels back",
        "vertical quilt lines",
        "column tufting",
        "vertical seam quilting",
        "tube quilting",
        "vertical paneled tuft",
        "rail-style tuft",
        "pillar tufting",
        "vector quilt lines",
        "vertical panel quilt",
        "vertical grid quilting",
        "vertical back channels"
    ],
    "External Back Quilted":
    [
        "externally quilted back",
        "quilted exterior back",
        "outside quilt back",
        "outer quilted backrest",
        "back exterior quilting",
        "external quilting back",
        "back exterior quilt",
        "quilted-back outside",
        "back quilt exterior",
        "exterior quilt back",
        "external tufted back",
        "outer tufting back",
        "outside tufted back",
        "outer panel quilt back",
        "external paneled quilt back",
        "external grid quilt back",
        "external diamond quilt back",
        "external channel quilt back",
        "external box tuft back",
        "external stitch quilt back",
        "external quilt pattern back",
        "external seam quilt back",
        "external rail quilt back",
        "external vertical quilt back",
        "external horizontal quilt back"
    ],
    "Straight": 
    [
        "linear",
        "unbending",    
        "straight back",
        "straight-edged",
        "straightforward",
        "unwavering",
        "unbending",
        "uncurved",
        "unbending",
    ],
    "With Movable Headrest": 
    [
        "with adjustable headrest",
        "movable head support",
        "detachable headrest",
        "headrest included",
        "with pivot headrest",
        "with tilting headrest",
        "with swiveling headrest",
        "headrest attachment",
        "with flip-up headrest",
        "with extendable headrest",
        "with modular headrest",
        "with removable headrest",
        "with sliding headrest",
        "with movable pillow rest",
        "with headrest functionality",
        "with headrest option",
        "with headrest module",
        "with articulated headrest",
        "with jointed headrest",
        "with flex headrest",
        "with adjustable neck rest",
        "with head support rest",
        "with repositionable headrest",
        "headrest flexibility",
        "with movable head cushion"
    ],
}